pingotron/accounts/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib.auth import views as auth_views
admin.autodiscover()

urlpatterns = patterns('',
     url(r'^login/$',
         auth_views.login,
         {'template_name': 'accounts/login.html'},
         name='auth_login'),
     url(r'^logout/$',
         auth_views.logout,
         {'template_name': 'accounts/logout.html'},
         name='auth_logout'),
     url(r'^password/change/$',
         auth_views.password_change,
         name='auth_password_change'),
     url(r'^password/change/done/$',
         auth_views.password_change_done,
         name='auth_password_change_done'),
     url(r'^password/reset/$',
         auth_views.password_reset,
         name='auth_password_reset'),
     url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
         auth_views.password_reset_confirm,
         name='auth_password_reset_confirm'),
     url(r'^password/reset/complete/$',
         auth_views.password_reset_complete,
         name='auth_password_reset_complete'),
     url(r'^password/reset/done/$',
         auth_views.password_reset_done,
         name='auth_password_reset_done'),
)

pingotron/record/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('pingotron.record.views',
    url(r'^$', 'overview'),
    url(r'^game/$', 'create_game'),
    url(r'^profile/$', 'edit_profile')
)

pingotron/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.auth import views as auth_views
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pingotron.views.home', name='home'),
    (r'^', include('pingotron.record.urls')),
    (r'^', include('pingotron.accounts.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
     url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
     url(r'^admin/', include(admin.site.urls)),
)

pingotron/accounts/models.py
from django.db import models

# Create your models here.

pingotron/record/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class PlayerProfile(models.Model):
    user = models.OneToOneField(User)
    alias = models.CharField(max_length=200, blank=True)
    avatar = models.ImageField(upload_to="avatar", blank=True)
    quote = models.CharField(max_length=240, blank=True)

    def __unicode__(self):
        if self.alias:
            return self.alias
        else:
            return self.user.username
    class Meta:
        verbose_name_plural = "Player Profiles"

# Django-Profiles stuff: https://bitbucket.org/ubernostrum/django-profiles/src/tip/docs/overview.txt
def create_player_with_user(sender, **kwargs):
    """When creating a new user, make a profile for him or her."""
    u = kwargs["instance"]
    if not PlayerProfile.objects.filter(user=u):
        PlayerProfile(user=u).save()

# Signal - Create PlayerProfile when User is created
post_save.connect(create_player_with_user, sender=User)

class Game(models.Model):
    winner = models.ForeignKey(User, related_name='win')
    winnerScore = models.IntegerField()
    loser = models.ForeignKey(User, related_name='loss')
    loserScore = models.IntegerField()
    targetScore = models.IntegerField(default="11", choices=((11, 11),(21, 21))) #What score you're playing to
    gameDateTime = models.DateTimeField(default=datetime.datetime.now(), blank=True)

    dateCreated = models.DateTimeField(default=datetime.datetime.now(), auto_now_add=True)
    #createdBy = models.ForeignKey(User, related_name="created%(app_label)s_%(class)s_related")

    lastModified = models.DateTimeField(blank=True, null=True)
    #modifiedBy = models.ForeignKey(User, related_name="modified%(app_label)s_%(class)s_related", blank=True, null=True)

    UNITS = (
        (u'B', u'Standard Beer Units'),
        (u'$', u'Dollars'),
        (u'L', u'Lunch'),
        (u'JJ', u'Jimmy John\'s'),
    )
    stakeValue = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    stakeUnit = models.CharField(max_length=2,choices=UNITS, blank=True, null=True)

    def save(self, **kwargs):
        """
        Some basic last-minute validation and fill in possible missing data.
        Data should fully be cleaned at the form: https://docs.djangoproject.com/en/1.1/ref/forms/validation/#form-field-default-cleaning
        """
        if not self.datetime:
            self.datetime = datetime.datetime.now()
        super(Game, self).save()

    def __unicode__(self):
        if self.stakeValue:
            return "%s - %s (%s) vs %s (%s) for %s %s" % (self.datetime.strftime('%Y-%m-%d %I:%M%p'), self.winner, self.winnerScore, self.loser, self.loserScore, self.stakeValue, self.stakeUnit)
        else:
            return "%s - %s (%s) vs %s (%s)" % (self.datetime.strftime('%Y-%m-%d %I:%M%p'), self.winner, self.winnerScore, self.loser, self.loserScore)

pingotron/record/forms.py
from django.db import models
from django import forms
from pingotron.record.models import *

class EditProfile(forms.ModelForm):
	class Meta:
		model = PlayerProfile

class CreateGameForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        return super(CreateGameForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Game
    def clean(self):
        cleaned_data = super(CreateGameForm, self).clean()

        # If score difference isn't greater than 2 points, raise exception
        if not abs(self.cleaned_data['winnerScore'] - self.cleaned_data['loserScore']) >= 2:
            raise forms.ValidationError("A player must win by at least 2 points")

        # If loser has higher score than winner, switch loser and winner
        if (self.cleaned_data['loserScore'] > self.cleaned_data['winnerScore']):
            self.cleaned_data['winner'], self.cleaned_data['loser'] = self.cleaned_data['loser'], self.cleaned_data['winner']
            self.cleaned_data['loserScore'], self.cleaned_data['winnerScore'] = self.cleaned_data['winnerScore'],self.cleaned_data['loserScore']

        # If stake value given but no stake unit, or vice versa, raise exception
        if (bool(self.cleaned_data['stakeValue']) != bool(self.cleaned_data['stakeUnit'])):
            raise forms.ValidationError("Stake value and units do not match up (one given without the other)")
        return cleaned_data

    def save(self, request):
        obj = super(CreateGameForm, self).save(commit=False)
        obj.createdBy = request.user
        obj.save()

pingotron/accounts/views.py
# Create your views here.

pingotron/record/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from pingotron.record.forms import *

@login_required
def overview(request):
    return HttpResponse('<p>Some day this will be stats overview</p>')

@login_required
def create_game(request):
    if request.method == 'POST': # If the form has been submitted...
        form = CreateGameForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            game = form.save(commit=False)
            #game.createdBy = request.user
            #game.modifiedBy = request.user
            game.save()
            return HttpResponse('<p>Form saved!</p>')
        else:
            raise
    else:
        form = CreateGameForm() # An unbound form
    return render(request, 'record/create_game.html', {'form': form,})

@login_required
def edit_profile(request):
    profile = get_object_or_404(PlayerProfile, user=request.user)
    if request.method == 'POST': # If the form has been submitted...
        form = EditProfile(request.POST, instance=profile) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            form.save()
            return HttpResponse('<p>Form saved!</p>')
        else:
            raise
    else:
        form = EditProfile(instance=profile) # An unbound form
    return render(request, 'accounts/edit_profile.html', {'user': request.user, 'form': form,})

pingotron/templates/accounts/edit_profile.html
{% extends "base.html" %}

{% block content %}
<h1>{{ user }}{% if user.alias %} aka {{ user.alias }}{% endif %}</h1>
<form method="post">{% csrf_token %}
<div>
    <div id="alias">
        <label for="id_alias">Alias</label>
        <div>{{ form.alias }}</div>
    </div>
    <div id="avatar">
        <label for="id_avatar">Avatar</label>
        <div>{{ form.avatar }}</div>
    </div>
    <div id="quote">
        <label for="id_quote">Quote</label>
        <div>{{ form.quote }}</div>
    </div>
</div>
<input type="submit" value="Submit" />
</form>
{% endblock content %}

pingotron/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h1>Login</h1>
<form method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock content %}

pingotron/templates/accounts/logout.html
{% extends "base.html" %}

{% block content %}
<h1>Logout</h1>
{% endblock content %}

pingotron/templates/base.html
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <link rel="stylesheet" href="css/normalize.min.css">
        <link rel="stylesheet" href="css/main.css">

        <script src="js/vendor/modernizr-2.6.1.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
        <![endif]-->

        {% block content %}
        {% endblock content %}

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.8.2.min.js"><\/script>')</script>

        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>

        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>

pingotron/templates/profiles/create_profile.html
{% extends "base.html" %}

{% block content %}

{% endblock content %}

pingotron/templates/profiles/edit_profile.html
{% extends "base.html" %}

{% block content %}
<h1>{{ user }}</h1>
<form method="post">{% csrf_token %}
<div>
    <div id="alias">
        <label for="id_alias">Alias</label>
        <div>{{ form.alias }}</div>
    </div>
    <div id="avatar">
        <label for="id_avatar">Avatar</label>
        <div>{{ form.avatar }}</div>
    </div>
    <div id="quote">
        <label for="id_quote">Quote</label>
        <div>{{ form.quote }}</div>
    </div>
</div>
<input type="submit" value="Submit" />
</form>
{% endblock content %}

pingotron/templates/record/create_game.html
{% extends "base.html" %}

{% block content %}
<h1>Game Form</h1>
<form method="post">{% csrf_token %}
{{ form.non_field_errors }}
<div>
    <div id="winner">
        <label for="id_winner">PlayerA</label>
        {{ form.winner.errors }}
        <div>{{ form.winner }}</div>
        {{ form.winnerScore.errors }}
        <div>{{ form.winnerScore }}</div>
    </div>
    <div id="loser">
        <label for="id_loser">PlayerB</label>
        {{ form.loser.errors }}
        <div>{{ form.loser }}</div>
        {{ form.loserScore.errors }}
        <div>{{ form.loserScore }}</div>
    </div>
    <div id="other">
        <label for="id_targetScore">Target Score</label>
        {{ form.targetScore.errors }}
        <div>{{ form.targetScore }}</div>
        <label>DateTime</label>
        {{ form.gameDateTime.errors }}
        <div>{{ form.gameDateTime }}</div>
    </div>
    <div id="stake">
        <label for="id_stakeValue">Stake</label>
        {{ form.stakeValue.errors }}
        <div>{{ form.stakeValue }}</div>
        {{ form.stakeUnit.errors }}
        <div>{{ form.stakeUnit }}</div>
    </div>
</div>
<input type="submit" value="Submit" />
</form>

{% endblock content %}